JokesWebApp/Models/ErrorViewModel.cs
using System;

namespace JokesWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

JokesWebApp/Models/Joke.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace JokesWebApp.Models
{
    public class Joke
    {
        public int Id { get; set; }
        public string JokeQuetion { get; set; }
        public string JokeAnswer { get; set; }

        public Joke()
        {

        }
    }
}

JokesWebApp/Controllers/HomeController.cs
using JokesWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace JokesWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult NewsFeed()
        {
            return View();
        }

        public IActionResult gifs()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

JokesWebApp/Controllers/JokesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JokesWebApp.Data;
using JokesWebApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace JokesWebApp.Controllers
{
    public class JokesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public JokesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Jokes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Joke.ToListAsync());
        }

        // GET: Show Search Form
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }


        // POST: Show Search Results
        public async Task<IActionResult> ShowSearchResults(string SearchPhrase)
        {
            return View("Index", await _context.Joke.Where(j => j.JokeQuetion.Contains(SearchPhrase)).ToListAsync());
        }

        // GET: Jokes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var joke = await _context.Joke
                .FirstOrDefaultAsync(m => m.Id == id);
            if (joke == null)
            {
                return NotFound();
            }

            return View(joke);
        }

        // GET: Jokes/Create

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Jokes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize] // put data in the database
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,JokeQuetion,JokeAnswer")] Joke joke)
        {
            if (ModelState.IsValid)
            {
                _context.Add(joke);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(joke);
        }

        // GET: Jokes/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var joke = await _context.Joke.FindAsync(id);
            if (joke == null)
            {
                return NotFound();
            }
            return View(joke);
        }

        // POST: Jokes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,JokeQuetion,JokeAnswer")] Joke joke)
        {
            if (id != joke.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(joke);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JokeExists(joke.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(joke);
        }

        // GET: Jokes/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var joke = await _context.Joke
                .FirstOrDefaultAsync(m => m.Id == id);
            if (joke == null)
            {
                return NotFound();
            }

            return View(joke);
        }

        // POST: Jokes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var joke = await _context.Joke.FindAsync(id);
            _context.Joke.Remove(joke);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JokeExists(int id)
        {
            return _context.Joke.Any(e => e.Id == id);
        }
    }
}

JokesWebApp/Views/Food.cshtml
@{
    ViewData["Title"] = "Food";
}

<h1>Food</h1>

JokesWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4" style="
        font-family: Arial;
        font-size: 30px;
">
        Friends and Gifs
    </h1>


    <img src="website_logo.jpg">

</div>

JokesWebApp/Views/Home/NewsFeed.cshtml
@{
    ViewData["Title"] = "NewsFeed";
}

<h1>NewsFeed</h1>
<br />
<table class="post-one" border="1" width="600px" height="400px"align="center">
    <tr >
        <th>Image of the post</th>
    </tr>
    <tr>
        <th>blaha blah blah here is post one blah blah</th>
    </tr>
</table>
<br />
<table class="post-two" border="1" width="600px" height="400px" align="center">
    <tr>
        <th>Image of the post</th>
    </tr>
    <tr>
        <th>blah blah blah here is post two blah</th>
    </tr>
</table>

JokesWebApp/Views/Home/gifs.cshtml
@{
    ViewData["Title"] = "gifs";
}

<h1>gifs</h1>

<table style="width:100%">

    
</table>

JokesWebApp/Views/Jokes/Create.cshtml
@model JokesWebApp.Models.Joke

@{
    ViewData["Title"] = "Create";
}

<h1>Add a friend</h1>

<h4>Joke</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="JokeQuetion" class="control-label">Name</label>
                <input asp-for="JokeQuetion" class="form-control" />
                <span asp-validation-for="JokeQuetion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JokeAnswer" class="control-label">Send Friend Request</label>
                <input asp-for="JokeAnswer" class="form-control" />
                <span asp-validation-for="JokeAnswer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to list of friends</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JokesWebApp/Views/Jokes/Delete.cshtml
@model JokesWebApp.Models.Joke

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Joke</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JokeQuetion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JokeQuetion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JokeAnswer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JokeAnswer)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

JokesWebApp/Views/Jokes/Details.cshtml
@model JokesWebApp.Models.Joke

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
 
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JokeQuetion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JokeQuetion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JokeAnswer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JokeAnswer)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to list of friends </a>
</div>

JokesWebApp/Views/Jokes/Edit.cshtml
@model JokesWebApp.Models.Joke

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit the question</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="JokeQuetion" class="control-label">Question</label>
                <input asp-for="JokeQuetion" class="form-control" />
                <span asp-validation-for="JokeQuetion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JokeAnswer" class="control-label">Answer</label>
                <input asp-for="JokeAnswer" class="form-control" />
                <span asp-validation-for="JokeAnswer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JokesWebApp/Views/Jokes/Index.cshtml
@model IEnumerable<JokesWebApp.Models.Joke>

@{
    ViewData["Title"] = "Index";
}

<h1>Here are your friends</h1>

<p>
    <a asp-action="Create">Add or remove a friend</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.JokeQuetion)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.JokeQuetion)
            </td>

            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit your friendship</a> |
                <a asp-action="Details" asp-route-id="@item.Id">View their profile</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Remove Friend</a>
            </td>
        </tr>
}
    </tbody>
</table>

JokesWebApp/Views/Jokes/ShowSearchForm.cshtml
<h4>search for anything on the site</h4>



<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">
            <div class="form-group">
                <label name="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control" />

            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index">Back to home</a>
</div>

JokesWebApp/Views/NewFolder/NewsFeed.cshtml
@model JokesWebApp.Models.Joke
@{
    ViewData["Title"] = "NewsFeed";
}

<h1>NewsFeed</h1>

JokesWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Friends and Gifs </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Friends and Gifs</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <img src="C:\Users\lets_\source\repos\Questions_and_Answers\JokesWebApp\Views\Shared\website_logo.jpg">
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Wall</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jokes" asp-action="Index">Friends</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=" " asp-controller="Jokes" asp-action="ShowSearchForm">Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=" " asp-controller="Home" asp-action="NewsFeed">News Feed</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=" " asp-controller="Home" asp-action="gifs">gifs</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Side navigation -->
    <div class="sidenav">
        <p class="categories">Explore</p>
        <a href="https://localhost:44322/Jokes">Food</a>
        <a href="https://localhost:44322/Jokes">Technology</a>
        <a href="https://localhost:44322/Jokes">Travel</a>
        <a href="https://localhost:44322/Jokes">Educational</a>
        <a href="https://localhost:44322/Jokes">Health</a>
        <a href="https://localhost:44322/Jokes">gifs</a>
        <a href="https://localhost:44322/Jokes">Sports</a>
        <a href="https://localhost:44322/Jokes">Entertainment</a>
        <a href="https://localhost:44322/Jokes">Music</a>
        <a href="https://localhost:44322/Jokes">Animals</a>
        <a href="https://localhost:44322/Jokes">Social Media</a>
        <a href="https://localhost:44322/Jokes">Pictures</a>
        <a href="https://localhost:44322/Jokes">Exercise</a>
    </div>

    <div class="leaderboard">
        <p class="categories">Top Friends</p>
        <a href="https://localhost:44322/Jokes">user 1</a>
        <a href="https://localhost:44322/Jokes">user 2</a>
        <a href="https://localhost:44322/Jokes">user 3</a>
        <a href="https://localhost:44322/Jokes">user 4</a>
        <a href="https://localhost:44322/Jokes">user 5</a>
        <a href="https://localhost:44322/Jokes">user 6</a>
        <a href="https://localhost:44322/Jokes">user 7</a>
        <a href="https://localhost:44322/Jokes">user 8</a>
        <a href="https://localhost:44322/Jokes">user 9</a>
        <a href="https://localhost:44322/Jokes">user 10</a>

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Friends and Gifs <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>